version: '3.3'

services:
  mongo:
    image: mongo:4.2.12-bionic
    container_name: chat-api-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: chat-api
    volumes:
      - ./database:/database
      - ./.db-data/mongodb:/data/db
      - ./.db-data/mongoconfig:/data/configdb
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null

  chat-api:
    image: chat-api
    container_name: app-chat-api
    build:
      context: .
      args:
        - COMMIT_HASH=COMMIT_HASH
      dockerfile: ./apps/chat-api/dockerfile
    environment:
      APP_PORT: 4000
      NODE_ENV: production
      APP_HOST: 0.0.0.0
      DATABASE_URL: mongodb://mongo:mongo@mongo:27017/chat-api?authSource=admin
      THROTTLE_TTL: 60
      THROTTLE_LIMIT: 10
      JWT_KEY: thisislongjwtkeyconfiguration
      REFRESH_TOKEN_TTL_LONG_LIVED: 2_592_000
      REFRESH_TOKEN_TTL: 86_400
      JWT_TTL: 900
      OPEN_API_KEY: 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
    ports:
      - 4005:4000
    depends_on:
      - mongo
