version: '3.3'

services:
  mongo:
    image: mongo:4.2.12-bionic
    container_name: chat-api-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: chat-api
    volumes:
      - ./database:/database
      - ./.db-data/mongodb:/data/db
      - ./.db-data/mongoconfig:/data/configdb
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null

  chat-api:
    image: chat-api
    container_name: app-chat-api
    build:
      context: .
      args:
        - COMMIT_HASH=COMMIT_HASH
      dockerfile: ./apps/chat-api/dockerfile
    environment:
      APP_PORT: 3000
      NODE_ENV: production
      DATABASE_URL: mongodb://mongo:mongo@mongo/chat-api?authSource=admin
    ports:
      - 4000:3000
    depends_on:
      - mongo
