# Install package dependencies
FROM node:16-alpine AS dependency

WORKDIR /chat-api

COPY package*.json ./
RUN npm ci

# Build source
FROM dependency AS base
COPY . .

# Build source
FROM base AS build
RUN npm run build:chat-api

# Ship compiled sources
FROM dependency

COPY --from=build /chat-api/dist ./dist

RUN npm prune --production

EXPOSE 4000
ENV NO_COLOR=true

ARG COMMIT_HASH
ENV COMMIT_HASH=$COMMIT_HASH

CMD ["node", "dist/apps/chat-api/main"]
