# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm i

      - name: Create env file
        run: |
          working-directory: ./apps/chat-api
          run: cp .env.example .env
          echo OPEN_API_KEY=${{ secrets.OPEN_API_KEY }} >> .env
          cat .env  

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test:compose
